{% set name = "types-kazoo" %}
{% set version = "0.1.2" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/types-kazoo-{{ version }}.tar.gz
  sha256: 7074df963a9439f17a705e8f24369187c564930cf8d8755c4b2ebab338b6fe8f

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - python >=3.6

test:
  commands:
    - test -f $SP_DIR/kazoo-stubs/__init__.pyi


about:
  home: https://github.com/python/typeshed
  summary: Typing stubs for kazoo
  license: Apache-2.0 AND MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - fhoehle
    - conda-forge/mypy
